### ISSUE TITLE
收到验证码后转发前smsForward.py 44行报错

### ISSUE THREAD

**Issue by invinciberry** [KooriMoe/Gammu-Wechat#4]
收到含有“验证码”三个字的短信后，log中44行报错。
在禁用smsForward.py 43-47行后暂时解决。

**Comment by KooriMoe** [comment]
烦请提供下报错内容，因为在我这边的测试环境并没有遇到这个问题，验证码是可以正常提取的。
![image](https://user-images.githubusercontent.com/39030261/133859633-4ab1d11f-2589-4e26-aa68-0b71f1f53ca0.jpeg)

**Comment by invinciberry** [comment]
这是我在log里看到的：

Thu 2021/09/23 13:24:44 gammu-smsd[7133]: Received message from: 10690759300410690456
Thu 2021/09/23 13:24:44 gammu-smsd[7133]: Read 1 messages
Thu 2021/09/23 13:24:44 gammu-smsd[7133]: Received IN20210923_202430_00_10690759300410690456_00.txt
Thu 2021/09/23 13:24:44 gammu-smsd[28136]: Starting run on receive: /usr/bin/python3 /home/pi/tools/smsForward.py IN20210923_202430_00_10690759300410690456_00.txt
Thu 2021/09/23 13:24:44 gammu-smsd[7133]: Process failed with exit status 1
Thu 2021/09/23 13:24:44 gammu-smsd[7133]: Subprocess output: Traceback (most recent call last):
  File "/home/pi/tools/smsForward.py", line 44, in <module>
    captchaCode = ','.join(re.findall("\d{6}|\d{4}", text))
NameError: name 're' is not defined

禁用smsForward.py 43-47行后收到的转发：
![image](https://user-images.githubusercontent.com/30306206/134508233-2c4c167e-e004-4c29-a2ce-e31d7f609f6a.png)

**Comment by invinciberry** [comment]
用了点脑子之后解决了，smsForward里面要import re
